import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '../_lib/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Leaderboard',
  description: 'Generated by create next app',
}

export default function LeaderBoardLayout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
