import { Chokokutai, Inter } from "next/font/google";
import "../../globals.css";
import Header from "../../_lib/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Treasure",
  description: "Generated by create next app",
};

export default function TreasureLayout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
