import { Inter } from "next/font/google";
import { AvatarContextProvider } from "./_lib/AvatarContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Treasure Hunt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/magikarp.png"></link>
      <body className={inter.className}>
        <AvatarContextProvider>{children}</AvatarContextProvider>
      </body>
    </html>
  );
}
