import { Chokokutai, Inter } from "next/font/google";
import "../globals.css";
import Header from "../_lib/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
